2022-08-24T16:25:41.263334+0300 An error has been caught in function 'notify', process 'MainProcess' (42911), thread 'MainThread' (140737053975488):
Traceback (most recent call last):

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/server.py", line 99, in <module>
    executor.start_polling(dp, skip_updates=True)
    │        │             └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x114724b20>
    │        └ <function start_polling at 0x10b29db80>
    └ <module 'aiogram.utils.executor' from '/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-...

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/utils/executor.py", line 45, in start_polling
    executor.start_polling(
    │        └ <function Executor.start_polling at 0x10b2a55e0>
    └ <aiogram.utils.executor.Executor object at 0x114749880>
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/utils/executor.py", line 323, in start_polling
    loop.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x10a3f9f70>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x10a3fdaf0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x10a37bc10>
    └ <Handle <TaskWakeupMethWrapper object at 0x11477a280>(<Future finished result=None>)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x11477a280>(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x11477a280>(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x11477a280>(<Future finished result=None>)>
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Update {"update_id": 135381659, "message": {"message_id": 588, "from": {"id": 227138434, "is_bot": false, "first_name": "Ma...
                     │           └ <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x114724b20>>
                     └ Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x1...
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
                 │    │                │      │      └ <aiogram.types.fields.Field object at 0x10b0a2190>
                 │    │                │      └ <Update {"update_id": 135381659, "message": {"message_id": 588, "from": {"id": 227138434, "is_bot": false, "first_name": "Max...
                 │    │                └ <function Handler.notify at 0x10b141d30>
                 │    └ <aiogram.dispatcher.handler.Handler object at 0x114724c40>
                 └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x114724b20>
> File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Message {"message_id": 588, "from": {"id": 227138434, "is_bot": false, "first_name": "Max", "last_name": "Malyshev", "usern...
                     │           └ <function weather_by_city at 0x114754700>
                     └ Handler.HandlerObj(handler=<function weather_by_city at 0x114754700>, spec=FullArgSpec(args=['message'], varargs=None, varkw=...

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/server.py", line 96, in weather_by_city
    raise WrongInput('City is not defined')
          └ <class 'exceptions.WrongInput'>

exceptions.WrongInput: City is not defined
2022-08-24T16:27:04.564103+0300 An error has been caught in function 'notify', process 'MainProcess' (42911), thread 'MainThread' (140737053975488):
Traceback (most recent call last):

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/server.py", line 99, in <module>
    executor.start_polling(dp, skip_updates=True)
    │        │             └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x114724b20>
    │        └ <function start_polling at 0x10b29db80>
    └ <module 'aiogram.utils.executor' from '/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-...

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/utils/executor.py", line 45, in start_polling
    executor.start_polling(
    │        └ <function Executor.start_polling at 0x10b2a55e0>
    └ <aiogram.utils.executor.Executor object at 0x114749880>
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/utils/executor.py", line 323, in start_polling
    loop.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x10a3f9f70>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x10a3fdaf0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x10a37bc10>
    └ <Handle <TaskWakeupMethWrapper object at 0x1147f1910>(<Future finished result=None>)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x1147f1910>(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x1147f1910>(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x1147f1910>(<Future finished result=None>)>
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Update {"update_id": 135381661, "message": {"message_id": 592, "from": {"id": 227138434, "is_bot": false, "first_name": "Ma...
                     │           └ <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x114724b20>>
                     └ Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x1...
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
                 │    │                │      │      └ <aiogram.types.fields.Field object at 0x10b0a2190>
                 │    │                │      └ <Update {"update_id": 135381661, "message": {"message_id": 592, "from": {"id": 227138434, "is_bot": false, "first_name": "Max...
                 │    │                └ <function Handler.notify at 0x10b141d30>
                 │    └ <aiogram.dispatcher.handler.Handler object at 0x114724c40>
                 └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x114724b20>
> File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Message {"message_id": 592, "from": {"id": 227138434, "is_bot": false, "first_name": "Max", "last_name": "Malyshev", "usern...
                     │           └ <function weather_by_city at 0x114754700>
                     └ Handler.HandlerObj(handler=<function weather_by_city at 0x114754700>, spec=FullArgSpec(args=['message'], varargs=None, varkw=...

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/server.py", line 96, in weather_by_city
    raise WrongInput('City is not defined')
          └ <class 'exceptions.WrongInput'>

exceptions.WrongInput: City is not defined
2022-08-24T16:29:22.629436+0300 ERROR An error has been caught in function 'notify', process 'MainProcess' (43152), thread 'MainThread' (140737053975488):
Traceback (most recent call last):

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/server.py", line 100, in <module>
    executor.start_polling(dp, skip_updates=True)
    │        │             └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x117f35a90>
    │        └ <function start_polling at 0x10eab4b80>
    └ <module 'aiogram.utils.executor' from '/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-...

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/utils/executor.py", line 45, in start_polling
    executor.start_polling(
    │        └ <function Executor.start_polling at 0x10eabc5e0>
    └ <aiogram.utils.executor.Executor object at 0x117f5a7f0>
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/utils/executor.py", line 323, in start_polling
    loop.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x10dc10f70>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x10dc14af0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x10db92c10>
    └ <Handle <TaskWakeupMethWrapper object at 0x117f8c1f0>(<Future finished result=None>)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x117f8c1f0>(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x117f8c1f0>(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x117f8c1f0>(<Future finished result=None>)>
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Update {"update_id": 135381662, "message": {"message_id": 594, "from": {"id": 227138434, "is_bot": false, "first_name": "Ma...
                     │           └ <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x117f35a90>>
                     └ Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x1...
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
                 │    │                │      │      └ <aiogram.types.fields.Field object at 0x10e8b9100>
                 │    │                │      └ <Update {"update_id": 135381662, "message": {"message_id": 594, "from": {"id": 227138434, "is_bot": false, "first_name": "Max...
                 │    │                └ <function Handler.notify at 0x10e958d30>
                 │    └ <aiogram.dispatcher.handler.Handler object at 0x117f35bb0>
                 └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x117f35a90>
> File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Message {"message_id": 594, "from": {"id": 227138434, "is_bot": false, "first_name": "Max", "last_name": "Malyshev", "usern...
                     │           └ <function weather_by_city at 0x117f65700>
                     └ Handler.HandlerObj(handler=<function weather_by_city at 0x117f65700>, spec=FullArgSpec(args=['message'], varargs=None, varkw=...

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/server.py", line 97, in weather_by_city
    raise WrongInput('City is not defined')
          └ <class 'exceptions.WrongInput'>

exceptions.WrongInput: City is not defined
2022-08-24T16:30:22.877245+0300 ERROR An error has been caught in function 'notify', process 'MainProcess' (43274), thread 'MainThread' (140737053975488):
Traceback (most recent call last):

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/server.py", line 100, in <module>
    executor.start_polling(dp, skip_updates=True)
    │        │             └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x10c850a60>
    │        └ <function start_polling at 0x10b42db80>
    └ <module 'aiogram.utils.executor' from '/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-...

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/utils/executor.py", line 45, in start_polling
    executor.start_polling(
    │        └ <function Executor.start_polling at 0x10b4355e0>
    └ <aiogram.utils.executor.Executor object at 0x10c8757c0>
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/utils/executor.py", line 323, in start_polling
    loop.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x10a589f70>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x10a58daf0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x10a50cc10>
    └ <Handle <TaskWakeupMethWrapper object at 0x10c8a71c0>(<Future finished result=None>)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x10c8a71c0>(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x10c8a71c0>(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x10c8a71c0>(<Future finished result=None>)>
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Update {"update_id": 135381663, "message": {"message_id": 596, "from": {"id": 227138434, "is_bot": false, "first_name": "Ma...
                     │           └ <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x10c850a60>>
                     └ Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x1...
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
                 │    │                │      │      └ <aiogram.types.fields.Field object at 0x10b2350d0>
                 │    │                │      └ <Update {"update_id": 135381663, "message": {"message_id": 596, "from": {"id": 227138434, "is_bot": false, "first_name": "Max...
                 │    │                └ <function Handler.notify at 0x10b2d2d30>
                 │    └ <aiogram.dispatcher.handler.Handler object at 0x10c850b80>
                 └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x10c850a60>
> File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Message {"message_id": 596, "from": {"id": 227138434, "is_bot": false, "first_name": "Max", "last_name": "Malyshev", "usern...
                     │           └ <function weather_by_city at 0x10c881700>
                     └ Handler.HandlerObj(handler=<function weather_by_city at 0x10c881700>, spec=FullArgSpec(args=['message'], varargs=None, varkw=...

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/server.py", line 97, in weather_by_city
    raise WrongInput('City is not defined')
          └ <class 'exceptions.WrongInput'>

exceptions.WrongInput: City is not defined
2022-08-24T16:31:33.478683+0300 ERROR An error has been caught in function 'notify', process 'MainProcess' (43371), thread 'MainThread' (140737053975488):
Traceback (most recent call last):

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/server.py", line 100, in <module>
    executor.start_polling(dp, skip_updates=True)
    │        │             └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x10b438a30>
    │        └ <function start_polling at 0x10a014b80>
    └ <module 'aiogram.utils.executor' from '/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-...

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/utils/executor.py", line 45, in start_polling
    executor.start_polling(
    │        └ <function Executor.start_polling at 0x10a01c5e0>
    └ <aiogram.utils.executor.Executor object at 0x10b45c790>
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/utils/executor.py", line 323, in start_polling
    loop.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x109170f70>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x109174af0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x1090f3c10>
    └ <Handle <TaskWakeupMethWrapper object at 0x10b48e190>(<Future finished result=None>)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x10b48e190>(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x10b48e190>(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x10b48e190>(<Future finished result=None>)>
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Update {"update_id": 135381664, "message": {"message_id": 598, "from": {"id": 227138434, "is_bot": false, "first_name": "Ma...
                     │           └ <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x10b438a30>>
                     └ Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x1...
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
                 │    │                │      │      └ <aiogram.types.fields.Field object at 0x109e1c0a0>
                 │    │                │      └ <Update {"update_id": 135381664, "message": {"message_id": 598, "from": {"id": 227138434, "is_bot": false, "first_name": "Max...
                 │    │                └ <function Handler.notify at 0x109eb9d30>
                 │    └ <aiogram.dispatcher.handler.Handler object at 0x10b438b50>
                 └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x10b438a30>
> File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Message {"message_id": 598, "from": {"id": 227138434, "is_bot": false, "first_name": "Max", "last_name": "Malyshev", "usern...
                     │           └ <function weather_by_city at 0x10b467700>
                     └ Handler.HandlerObj(handler=<function weather_by_city at 0x10b467700>, spec=FullArgSpec(args=['message'], varargs=None, varkw=...

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/server.py", line 97, in weather_by_city
    raise WrongInput('City is not defined')
          └ <class 'exceptions.WrongInput'>

exceptions.WrongInput: City is not defined
2022-08-24T16:45:42.890417+0300 ERROR An error has been caught in function 'notify', process 'MainProcess' (44173), thread 'MainThread' (140737053975488):
Traceback (most recent call last):

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/server.py", line 100, in <module>
    executor.start_polling(dp, skip_updates=True)
    │        │             └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x10bca9b50>
    │        └ <function start_polling at 0x108884b80>
    └ <module 'aiogram.utils.executor' from '/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-...

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/utils/executor.py", line 45, in start_polling
    executor.start_polling(
    │        └ <function Executor.start_polling at 0x10888c5e0>
    └ <aiogram.utils.executor.Executor object at 0x10bccc8b0>
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/utils/executor.py", line 323, in start_polling
    loop.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x1079e0f70>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x1079e4af0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x107963c10>
    └ <Handle <TaskWakeupMethWrapper object at 0x10bcfd2b0>(<Future finished result=None>)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x10bcfd2b0>(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x10bcfd2b0>(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x10bcfd2b0>(<Future finished result=None>)>
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Update {"update_id": 135381665, "message": {"message_id": 600, "from": {"id": 227138434, "is_bot": false, "first_name": "Ma...
                     │           └ <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x10bca9b50>>
                     └ Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x1...
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
                 │    │                │      │      └ <aiogram.types.fields.Field object at 0x1086891c0>
                 │    │                │      └ <Update {"update_id": 135381665, "message": {"message_id": 600, "from": {"id": 227138434, "is_bot": false, "first_name": "Max...
                 │    │                └ <function Handler.notify at 0x108728d30>
                 │    └ <aiogram.dispatcher.handler.Handler object at 0x10bca9c70>
                 └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x10bca9b50>
> File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Message {"message_id": 600, "from": {"id": 227138434, "is_bot": false, "first_name": "Max", "last_name": "Malyshev", "usern...
                     │           └ <function weather_by_city at 0x10bcd8700>
                     └ Handler.HandlerObj(handler=<function weather_by_city at 0x10bcd8700>, spec=FullArgSpec(args=['message'], varargs=None, varkw=...

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/server.py", line 97, in weather_by_city
    raise WrongInput('City is not defined')
          └ <class 'exceptions.WrongInput'>

exceptions.WrongInput: City is not defined
2022-08-24T16:46:29.410364+0300 ERROR An error has been caught in function 'notify', process 'MainProcess' (44257), thread 'MainThread' (140737053975488):
Traceback (most recent call last):

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/server.py", line 100, in <module>
    executor.start_polling(dp, skip_updates=True)
    │        │             └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x1199c7b50>
    │        └ <function start_polling at 0x110547af0>
    └ <module 'aiogram.utils.executor' from '/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-...

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/utils/executor.py", line 45, in start_polling
    executor.start_polling(
    │        └ <function Executor.start_polling at 0x11054f550>
    └ <aiogram.utils.executor.Executor object at 0x1199ea8b0>
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/utils/executor.py", line 323, in start_polling
    loop.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x10f6a3ee0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x10f6a7a60>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x10f625b80>
    └ <Handle <TaskWakeupMethWrapper object at 0x119a1b2b0>(<Future finished result=None>)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x119a1b2b0>(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x119a1b2b0>(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x119a1b2b0>(<Future finished result=None>)>
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Update {"update_id": 135381666, "message": {"message_id": 602, "from": {"id": 227138434, "is_bot": false, "first_name": "Ma...
                     │           └ <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x1199c7b50>>
                     └ Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x1...
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
                 │    │                │      │      └ <aiogram.types.fields.Field object at 0x11034d1c0>
                 │    │                │      └ <Update {"update_id": 135381666, "message": {"message_id": 602, "from": {"id": 227138434, "is_bot": false, "first_name": "Max...
                 │    │                └ <function Handler.notify at 0x1103eeca0>
                 │    └ <aiogram.dispatcher.handler.Handler object at 0x1199c7c70>
                 └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x1199c7b50>
> File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Message {"message_id": 602, "from": {"id": 227138434, "is_bot": false, "first_name": "Max", "last_name": "Malyshev", "usern...
                     │           └ <function weather_by_city at 0x1199f6670>
                     └ Handler.HandlerObj(handler=<function weather_by_city at 0x1199f6670>, spec=FullArgSpec(args=['message'], varargs=None, varkw=...

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/server.py", line 97, in weather_by_city
    raise WrongInput(f'City {message.text} is not defined')
          └ <class 'exceptions.WrongInput'>

exceptions.WrongInput: City By Unu h is not defined
2022-08-24T16:47:08.286708+0300 ERROR An error has been caught in function 'notify', process 'MainProcess' (44318), thread 'MainThread' (140737053975488):
Traceback (most recent call last):

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/server.py", line 100, in <module>
    executor.start_polling(dp, skip_updates=True)
    │        │             └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x113045bb0>
    │        └ <function start_polling at 0x109c52af0>
    └ <module 'aiogram.utils.executor' from '/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-...

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/utils/executor.py", line 45, in start_polling
    executor.start_polling(
    │        └ <function Executor.start_polling at 0x109c59550>
    └ <aiogram.utils.executor.Executor object at 0x11306a910>
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/utils/executor.py", line 323, in start_polling
    loop.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x108daeee0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x108db2a60>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x108d31b80>
    └ <Handle <TaskWakeupMethWrapper object at 0x11309a310>(<Future finished result=None>)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x11309a310>(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x11309a310>(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x11309a310>(<Future finished result=None>)>
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Update {"update_id": 135381668, "message": {"message_id": 605, "from": {"id": 227138434, "is_bot": false, "first_name": "Ma...
                     │           └ <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x113045bb0>>
                     └ Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x1...
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
                 │    │                │      │      └ <aiogram.types.fields.Field object at 0x109a58220>
                 │    │                │      └ <Update {"update_id": 135381668, "message": {"message_id": 605, "from": {"id": 227138434, "is_bot": false, "first_name": "Max...
                 │    │                └ <function Handler.notify at 0x109af9ca0>
                 │    └ <aiogram.dispatcher.handler.Handler object at 0x113045cd0>
                 └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x113045bb0>
> File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Message {"message_id": 605, "from": {"id": 227138434, "is_bot": false, "first_name": "Max", "last_name": "Malyshev", "usern...
                     │           └ <function weather_by_city at 0x113075670>
                     └ Handler.HandlerObj(handler=<function weather_by_city at 0x113075670>, spec=FullArgSpec(args=['message'], varargs=None, varkw=...

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/server.py", line 97, in weather_by_city
    raise WrongInput(f'City "{message.text}" is not defined')
          └ <class 'exceptions.WrongInput'>

exceptions.WrongInput: City "H h h Unu" is not defined
2022-08-24T16:54:47.864664+0300 ERROR An error has been caught in function 'notify', process 'MainProcess' (44318), thread 'MainThread' (140737053975488):
Traceback (most recent call last):

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/server.py", line 100, in <module>
    executor.start_polling(dp, skip_updates=True)
    │        │             └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x113045bb0>
    │        └ <function start_polling at 0x109c52af0>
    └ <module 'aiogram.utils.executor' from '/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-...

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/utils/executor.py", line 45, in start_polling
    executor.start_polling(
    │        └ <function Executor.start_polling at 0x109c59550>
    └ <aiogram.utils.executor.Executor object at 0x11306a910>
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/utils/executor.py", line 323, in start_polling
    loop.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x108daeee0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x108db2a60>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x108d31b80>
    └ <Handle <TaskWakeupMethWrapper object at 0x113112790>(<Future finished result=None>)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x113112790>(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x113112790>(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x113112790>(<Future finished result=None>)>
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Update {"update_id": 135381669, "message": {"message_id": 607, "from": {"id": 227138434, "is_bot": false, "first_name": "Ma...
                     │           └ <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x113045bb0>>
                     └ Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x1...
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
                 │    │                │      │      └ <aiogram.types.fields.Field object at 0x109a58220>
                 │    │                │      └ <Update {"update_id": 135381669, "message": {"message_id": 607, "from": {"id": 227138434, "is_bot": false, "first_name": "Max...
                 │    │                └ <function Handler.notify at 0x109af9ca0>
                 │    └ <aiogram.dispatcher.handler.Handler object at 0x113045cd0>
                 └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x113045bb0>
> File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Message {"message_id": 607, "from": {"id": 227138434, "is_bot": false, "first_name": "Max", "last_name": "Malyshev", "usern...
                     │           └ <function weather_by_city at 0x113075670>
                     └ Handler.HandlerObj(handler=<function weather_by_city at 0x113075670>, spec=FullArgSpec(args=['message'], varargs=None, varkw=...

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/server.py", line 97, in weather_by_city
    raise WrongInput(f'City "{message.text}" is not defined')
          └ <class 'exceptions.WrongInput'>

exceptions.WrongInput: City "Igor onidle" is not defined
2022-08-25T19:55:40.729352+0300 ERROR An error has been caught in function 'notify', process 'MainProcess' (91194), thread 'MainThread' (140737053975488):
Traceback (most recent call last):

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/server.py", line 102, in <module>
    executor.start_polling(dp, skip_updates=True)
    │        │             └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x1164b51c0>
    │        └ <function start_polling at 0x10d13e430>
    └ <module 'aiogram.utils.executor' from '/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-...

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/utils/executor.py", line 45, in start_polling
    executor.start_polling(
    │        └ <function Executor.start_polling at 0x10d13ee50>
    └ <aiogram.utils.executor.Executor object at 0x1164c06a0>
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/utils/executor.py", line 323, in start_polling
    loop.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x10c2ab5e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x10c2ae160>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x10bedb280>
    └ <Handle <TaskWakeupMethWrapper object at 0x1164fb310>(<Future finished result=None>)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x1164fb310>(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x1164fb310>(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x1164fb310>(<Future finished result=None>)>
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Update {"update_id": 135381671, "message": {"message_id": 611, "from": {"id": 227138434, "is_bot": false, "first_name": "Ma...
                     │           └ <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x1164b51c0>>
                     └ Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x1...
  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
                 │    │                │      │      └ <aiogram.types.fields.Field object at 0x10cf3fc70>
                 │    │                │      └ <Update {"update_id": 135381671, "message": {"message_id": 611, "from": {"id": 227138434, "is_bot": false, "first_name": "Max...
                 │    │                └ <function Handler.notify at 0x10cfe95e0>
                 │    └ <aiogram.dispatcher.handler.Handler object at 0x1164b5310>
                 └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x1164b51c0>
> File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/W_Teleg_env/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Message {"message_id": 611, "from": {"id": 227138434, "is_bot": false, "first_name": "Max", "last_name": "Malyshev", "usern...
                     │           └ <function weather_by_city at 0x1164ca790>
                     └ Handler.HandlerObj(handler=<function weather_by_city at 0x1164ca790>, spec=FullArgSpec(args=['message'], varargs=None, varkw=...

  File "/Users/maxim/Yandex.Disk.localized/WheatherAppTelegram/server.py", line 98, in weather_by_city
    raise WrongInput(f'City "{message.text}" is not defined')
          └ <class 'exceptions.WrongInput'>

exceptions.WrongInput: City "Jdd ex I island" is not defined
